AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-resume-challenge

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app/lambda_module.lambda_handler
      Runtime: python3.12
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable

      Policies:
      - Statement:
        - Sid: DDBDescribeTablePolicy
          Effect: Allow
          Action:
          - dynamodb:DescribeTable
          Resource: !GetAtt 'DynamoDBTable.Arn'

  VisitorsCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app/lambda_module.visit_handler
      Runtime: python3.12
      Events:
        HTTP:
          Type: Api
          Properties:
            Path: /visits
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Policies:
      - Statement:
        - Sid: DDBUpdateItemPolicy
          Effect: Allow
          Action:
          - dynamodb:UpdateItem
          Resource: !GetAtt 'DynamoDBTable.Arn'


  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  APIEndpoint:
    Description: "API Gateway endpoint for portfolio site lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  TableName:
    Description: "Name of the DynamoDB table"
    Value: !Ref DynamoDBTable
